[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "script-src 'self' https://www.google-analytics.com https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://shoonia.wixsite.com; img-src 'self' https://static.wixstatic.com https://www.google-analytics.com;"
